hp/urls.py
# 引入path
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'hp'

urlpatterns = [
     path('switch-list_100/', views.switch_list_100, name='switch_list_100'),
     path('switch-detail_100/<int:id>/', views.switch_detail_100, name='switch_detail_100'),
]

quick_search/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    #add
    path('hp/', include('hp.urls', namespace='hp')),
]

hp/models.py
from django.db import models

# Create your models here.
from django.db import models

class Tranceiver(models.Model):
	tranceiver_type = models.CharField(max_length=30)


	def __str__(self):
		return "%s" % (self.tranceiver_type)

class Switch_100M(models.Model):
	transceiver = models.ForeignKey(Tranceiver, on_delete=models.CASCADE)

	switch_model = models.CharField(max_length=100)

	HBASET = models.CharField(max_length=20)
	HFX = models.CharField(max_length=20)
	HLX = models.CharField(max_length=20, default='')
	HEX = models.CharField(max_length=20)
	HZX = models.CharField(max_length=20)
	HBD = models.CharField(max_length=20)
	HBU = models.CharField(max_length=20)


	def __str__(self):
		return self.switch_model

	class Meta:
		ordering = ['switch_model']


class Switch_1G(models.Model):
	transceiver = models.ForeignKey(Tranceiver, on_delete=models.CASCADE)

	switch_model = models.CharField(max_length=100)

	G_T = models.CharField(max_length=20)
	G_SX = models.CharField(max_length=20)
	G_LX = models.CharField(max_length=20)
	G_LH = models.CharField(max_length=20)
	G_EX = models.CharField(max_length=20)
	G_ZX = models.CharField(max_length=20)
	G_EZX_100KM = models.CharField(max_length=20)
	G_EZX_120KM = models.CharField(max_length=20)
	G_BD = models.CharField(max_length=20)
	G_BU = models.CharField(max_length=20)


	def __str__(self):
		return self.switch_model

	class Meta:
		ordering = ['switch_model']



class Switch_10G(models.Model):
	transceiver = models.ForeignKey(Tranceiver, on_delete=models.CASCADE)

	switch_model = models.CharField(max_length=100)

	SR = models.CharField(max_length=20)
	LRM = models.CharField(max_length=20)
	LR = models.CharField(max_length=20)
	ER = models.CharField(max_length=20)
	ZR = models.CharField(max_length=20)
	XFP_SR = models.CharField(max_length=20)
	XFP_LR = models.CharField(max_length=20)
	XFP_ER = models.CharField(max_length=20)
	XFP_ZR = models.CharField(max_length=20)
	DAC_05M = models.CharField(max_length=20)
	DAC_1M = models.CharField(max_length=20)
	DAC_3M = models.CharField(max_length=20)
	DAC_5M = models.CharField(max_length=20)
	DAC_7M = models.CharField(max_length=20)
	DAC_10M = models.CharField(max_length=20)
	DAC_15M = models.CharField(max_length=20)
	AOC_7M = models.CharField(max_length=20)
	AOC_10M = models.CharField(max_length=20)
	AOC_20M = models.CharField(max_length=20)
	X2_SR = models.CharField(max_length=20)
	X2_LRM = models.CharField(max_length=20)
	X2_LR = models.CharField(max_length=20)
	X2_ER = models.CharField(max_length=20)
	X2_ZR = models.CharField(max_length=20)



	def __str__(self):
		return self.switch_model

	class Meta:
		ordering = ['switch_model']

hp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Switch_100M
from django.db.models import Q

def switch_list_100(request):
    # 取出所有
    switches = Switch_100M.objects.all()
    category = 'HP/H3C 100M Transceiver Modules Lookup'
    # 需要传递给模板（templates）的对象
    context = { 'switches': switches, 
    'category': category }

    # render函数：载入模板，并返回context对象
    return render(request, 'hp/list.html', context)

def switch_detail_100(request, id):
    # 取出相应
    switch = Switch_100M.objects.get(id=id)
    # 需要传递给模板的对象
    context = { 'switch': switch }
    # 载入模板，并返回context对象
    return render(request, 'hp/detail.html', context)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Quick Lookup</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-2">Quick Lookup </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

  

            <!-- Divider -->
            <hr class="sidebar-divider">

    

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item active">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
                    aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>HP & H3C</span>
                </a>
                <div id="collapsePages" class="collapse show" aria-labelledby="headingPages"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                
                        <a class="collapse-item" href="{% url 'hp:switch_list_100'%}">100M</a>
                        <a class="collapse-item" href="register.html">1G</a>
                        <a class="collapse-item" href="forgot-password.html">10G</a>
                        <a class="collapse-item" href="login.html">25G</a>
                        <a class="collapse-item" href="login.html">100G</a>
                        
                    </div>
                </div>
            </li>


            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Compatibility Chart</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        
                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">


                    <!-- 预留具体页面的位置 -->
                    {% block content %}{% endblock content %}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Qiuck Lookup 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>



    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>

</body>

</html>

templates/hp/detail.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">{{ switch.switch_model }}</h1>
                        <a href="{% url 'hp:switch_list_100'%}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                                class="fas fa-chevron-left fa-sm text-white-50"></i> Back</a>
                    </div>

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">

                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <tbody>
                                        
                                        <tr>
                                            <th>100BASE-T</th>
                                            {% if switch.HBASET == '/' %} 
                                            <td>{{ switch.HBASET }}</td>
                                            {% else %}
                                            <td><a href="https://www.fs.com/index.php?main_page=advanced_search_result&keyword={{switch.HBASET}}&searchSubmit=Search" target="_blank" > {{ switch.HBASET }}</a></td>
                                            {% endif %}

                                        </tr>

                                        <tr>
                                            <th>100FX</th>
                                            {% if switch.HFX == '/' %}
                                            <td>{{ switch.HFX }}</td>
                                            {% else %}
                                            <td><a href="https://www.fs.com/index.php?main_page=advanced_search_result&keyword={{switch.HFX }}&searchSubmit=Search" target="_blank" >{{ switch.HFX }}</a></td>
                                            {% endif %}

                                        </tr>

                                        <tr>
                                            <th>100LX</th>
                                            {% if switch.HLX == '/' %}
                                            <td>{{ switch.HLX }}</td>
                                            {% else %}
                                            <td><a href="https://www.fs.com/index.php?main_page=advanced_search_result&keyword={{switch.HLX }}&searchSubmit=Search" target="_blank" >{{ switch.HLX }}</a></td>
                                            {% endif %}
                                        </tr>                                        
                                        <tr>
                                            <th>100EX</th>
                                            {% if switch.HEX == '/' %}
                                            <td>{{ switch.HEX }}</td>
                                            {% else %}
                                            <td><a href="https://www.fs.com/index.php?main_page=advanced_search_result&keyword={{switch.HEX }}&searchSubmit=Search" target="_blank" >{{ switch.HEX }}</a></td>
                                            {% endif %}

                                        </tr>

                                         <tr>
                                            <th>100ZX</th>
                                            {% if switch.HZX == '/' %}
                                            <td>{{ switch.HZX }}</td>
                                            {% else %}
                                            <td><a href="https://www.fs.com/index.php?main_page=advanced_search_result&keyword={{switch.HZX }}&searchSubmit=Search" target="_blank" >{{ switch.HZX }}</a></td>
                                            {% endif %}
                                        </tr>

                                        <tr>
                                            <th>100M BD</th>
                                            {% if switch.HBD == '/' %}
                                            <td>{{ switch.HBD }}</td>
                                            {% else %}
                                            <td><a href="https://www.fs.com/index.php?main_page=advanced_search_result&keyword={{switch.HBD }}&searchSubmit=Search" target="_blank" >{{ switch.HBD }}</a></td>
                                            {% endif %}

                                        </tr>

                                        <tr>
                                            <th>100M BU</th>
                                            {% if switch.HBU == '/' %}
                                            <td>{{ switch.HBU }}</td>
                                            {% else %}
                                            <td><a href="https://www.fs.com/index.php?main_page=advanced_search_result&keyword={{switch.HBU }}&searchSubmit=Search" target="_blank" >{{ switch.HBU }}</a></td>
                                            {% endif %}

                                        </tr>
                                        

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

{% endblock content %}

templates/hp/list.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">{{ category }}</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Switch Model</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Switch Model</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for switch in switches %}
                                        <tr>
                                        
                                            <td ><a href="{% url 'hp:switch_detail_100' switch.id %}" >{{ switch.switch_model }}</a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

{% endblock content %}